import {partnersData} from "./interfaces";
export const dataTeam: partnersData[] = [
    {
        id: 1,
        name: "Jon Snow",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 2,
        name: "Cersei Lannister",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 3,
        name: "Jaime Lannister",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 4,
        name: "Anya Stark",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 5,
        name: "Daenerys Targaryen",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 6,
        name: "Ever Melisandre",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 7,
        name: "Ferrara Clifford",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 8,
        name: "Rossini Frances",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 9,
        name: "Harvey Roxie",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 10,
        name: "Jon Snow",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 11,
        name: "Cersei Lannister",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 12,
        name: "Jaime Lannister",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 13,
        name: "Anya Stark",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 14,
        name: "Daenerys Targaryen",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 15,
        name: "Ever Melisandre",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 16,
        name: "Ferrara Clifford",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 17,
        name: "Rossini Frances",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 18,
        name: "Harvey Roxie",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
    {
        id: 19,
        name: "Rossini Frances",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "Active",
    },
    {
        id: 20,
        name: "Harvey Roxie",
        location: "London, United Kingdom",
        createdData: "01.12.2022 12:30",
        status: "inActive",
    },
];